#!/usr/bin/env ansible-playbook
---
- name: Start up the kind cluster
  hosts: localhost
  vars:
    cluster_name: opa
    container_name: opa-control-plane
    kubernetes_version: v1.23.0

  tasks:
  - import_tasks: ../ansible_tasks/setup_kind.yaml

- name: Setup cluster
  hosts: opa-control-plane
  connection: docker
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
  - import_tasks: ../ansible_tasks/setup_kubeconfig.yaml

  - name: Apply Gatekeeper Manifest
    command: kubectl create -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.7/deploy/gatekeeper.yaml