---
  - name: Ensure that the /root/.kube/ directory exits
    file:
      path: /root/.kube
      state: directory
    
  - name: Copy the kubeconfig to the default location
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /root/.kube/config
      remote_src: yes