#!/usr/bin/env ansible-playbook
---
- name: Start up the kind cluster
  hosts: localhost
  vars:
    cluster_name: kyverno
    container_name: kyverno-control-plane
    kubernetes_version: v1.23.0

  tasks:
  - import_tasks: ../ansible_tasks/setup_kind.yaml

- name: Setup cluster
  hosts: kyverno-control-plane
  connection: docker
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
  - import_tasks: ../ansible_tasks/setup_kubeconfig.yaml

  - name: Apply Kyverno Manifest
    command: helm install kyverno --namespace kyverno kyverno --create-namespace --repo https://kyverno.github.io/kyverno/