#!/usr/bin/env ansible-playbook
---
- name: Start up the kind cluster
  hosts: localhost
  vars:
    cluster_name: jspolicy
    container_name: jspolicy-control-plane
    kubernetes_version: v1.20.2

  tasks:
  - import_tasks: ../ansible_tasks/setup_kind.yaml

- name: Setup cluster
  hosts: jspolicy-control-plane
  connection: docker
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
  - import_tasks: ../ansible_tasks/setup_kubeconfig.yaml

  - name: Apply jsPolicy Manifest
    command: helm install jspolicy jspolicy -n jspolicy --create-namespace --repo https://charts.loft.sh